import { PrismaService } from '../../database/prisma.service';
import { AsaasService } from './asaas.service';
import { CreatePagamentoDto } from './dto/create-pagamento.dto';
export declare class PagamentosService {
    private prisma;
    private asaasService;
    constructor(prisma: PrismaService, asaasService: AsaasService);
    criarPagamento(dto: CreatePagamentoDto, empresaId: string): Promise<{
        qrCode: any;
        copyPaste: any;
        boletoUrl: any;
        invoiceUrl: any;
        id: string;
        pedidoId: string;
        empresaId: string;
        valor: number;
        metodo: string;
        status: string;
        transacaoId: string | null;
        asaasPaymentId: string | null;
        asaasInvoiceUrl: string | null;
        pixQrCode: string | null;
        pixCopyPaste: string | null;
        dataVencimento: Date | null;
        dataPagamento: Date | null;
        gatewayResposta: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    buscarPagamento(id: string, empresaId: string): Promise<{
        pedido: {
            id: string;
            numero: string;
            status: string;
            subtotal: number;
            desconto: number;
            total: number;
            frete: number;
            clienteId: string;
            empresaId: string;
            enderecoEntrega: string | null;
            formaPagamento: string | null;
            cupomDesconto: string | null;
            observacoes: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
    } & {
        id: string;
        pedidoId: string;
        empresaId: string;
        valor: number;
        metodo: string;
        status: string;
        transacaoId: string | null;
        asaasPaymentId: string | null;
        asaasInvoiceUrl: string | null;
        pixQrCode: string | null;
        pixCopyPaste: string | null;
        boletoUrl: string | null;
        dataVencimento: Date | null;
        dataPagamento: Date | null;
        gatewayResposta: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    buscarPagamentosPorPedido(pedidoId: string, empresaId: string): Promise<{
        id: string;
        pedidoId: string;
        empresaId: string;
        valor: number;
        metodo: string;
        status: string;
        transacaoId: string | null;
        asaasPaymentId: string | null;
        asaasInvoiceUrl: string | null;
        pixQrCode: string | null;
        pixCopyPaste: string | null;
        boletoUrl: string | null;
        dataVencimento: Date | null;
        dataPagamento: Date | null;
        gatewayResposta: string | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    buscarPagamentosEmpresa(empresaId: string): Promise<({
        pedido: {
            numero: string;
            total: number;
        };
    } & {
        id: string;
        pedidoId: string;
        empresaId: string;
        valor: number;
        metodo: string;
        status: string;
        transacaoId: string | null;
        asaasPaymentId: string | null;
        asaasInvoiceUrl: string | null;
        pixQrCode: string | null;
        pixCopyPaste: string | null;
        boletoUrl: string | null;
        dataVencimento: Date | null;
        dataPagamento: Date | null;
        gatewayResposta: string | null;
        createdAt: Date;
        updatedAt: Date;
    })[]>;
    cancelarPagamento(id: string, empresaId: string): Promise<{
        id: string;
        pedidoId: string;
        empresaId: string;
        valor: number;
        metodo: string;
        status: string;
        transacaoId: string | null;
        asaasPaymentId: string | null;
        asaasInvoiceUrl: string | null;
        pixQrCode: string | null;
        pixCopyPaste: string | null;
        boletoUrl: string | null;
        dataVencimento: Date | null;
        dataPagamento: Date | null;
        gatewayResposta: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    processarEventoAsaas(evento: any): Promise<void>;
}
